version: "3.8"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/app
      - /app/.venv
    command: uvicorn src.main:app --host 0.0.0.0

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    env_file:
      - .env
